version: "3"

services:
  scratch_gui:
    restart: always
    #image: test/scratch-gui:latest
    image: node:current-alpine3.16
    container_name: scratch_gui
    environment:
      - NODE_OPTIONS="--openssl-legacy-provider"
    ports:
      - 8601:8601
    volumes:
      - ./:/app
    working_dir: /app/scratch-gui
    command: >
      sh -c "npm install --force"
    profiles:
      - scratch_gui
