name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image to scratch project
      run: cp -rf ./github/Dockerfile . && cp -rf ./github/docker-compose.yml . docker-compose --profile scratch_gui up
